name: C# Linter
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Cache dotnet-format
        id: cache-dotnet-format
        uses: actions/cache@v4
        with:
          path: ~/.dotnet/tools
          key: dotnet-format-${{ github.sha }}  
          restore-keys: |
            dotnet-format-

      - name: Install dotnet-format
        if: steps.cache-dotnet-format.outputs.cache-hit == 'true'
        run: dotnet tool install -g dotnet-format

      - name: Run soft dotnet-format
        run: |
          echo "::group::Running dotnet-format"
          output=$(dotnet-format --check --verbosity diagnostic 2>&1 || true)
          echo "$output"
          echo "::endgroup::"
          ls -la
          echo "=== Processing output ==="
          echo "$output" | grep -E "error|warning" | while IFS= read -r line; do
            if [[ "$line" =~ ([^\(]+)\(([0-9]+),([0-9]+)\):[[:space:]](.*) ]]; then
              file="${BASH_REMATCH[1]}"
              line_num="${BASH_REMATCH[2]}"
              message="${BASH_REMATCH[4]}"
              echo "::warning file=$file,line=$line_num::$message"
            elif [[ "$line" =~ (error|warning)[[:space:]].+ ]]; then
              echo "::warning::$line"
            fi
          done
        
          echo "=== Lint completed ==="
