name: C# Linter
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Cache csharp-lint
        id: cache-csharp-lint
        uses: actions/cache@v4
        with:
          path: ~/.dotnet/tools
          key: csharp-lint-${{ github.sha }}  
          restore-keys: |
            csharp-lint-

      - name: Install csharp-lint
        if: steps.cache-csharp-lint.outputs.cache-hit == 'true'
        run: dotnet tool install -g csharp-lint

      - name: Run parsing
        run: |
          csharp-lint "**/*.cs" | while read -r line; do
          if [[ $line =~ ^(.*):([0-9]+):([0-9]+):\ (.*)$ ]]; then
            echo "::warning file=${BASH_REMATCH[1]},line=${BASH_REMATCH[2]},col=${BASH_REMATCH[3]}::${BASH_REMATCH[4]}"
          fi
          done
