name: Run Unity Tests

on:
  [push, workflow_dispatch]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library Folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ github.sha }}
          restore-keys: |
            Library-WebGL-

      - name: Cache Test History Folder
        uses: actions/cache@v4
        with:
          path: ${{ steps.TestStep.outputs.coveragePath }}/Report-history
          key: History-Test-${{ github.sha }}
          restore-keys: |
            History-Test-

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        id: TestStep
        env:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;generateHtmlReportHistory;assemblyFilters:+Assembly-CSharp;
          

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Results
          path: ${{ steps.TestStep.outputs.coveragePath }}
          
