name: Run Unity Tests

on:
  [push, workflow_dispatch]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        id: TestStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          coverageOptions: generateAdditionalMetrics; generateHtmlReport; generateBadgeReport; assemblyFilters:+Assembly-CSharp;
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ${{ steps.TestStep.outputs.artifactsPath }}

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Results
          path: ${{ steps.TestStep.outputs.coveragePath }}/Report/index.html
          
